/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/no-location`; params?: Router.UnknownInputParams; } | { pathname: `/offline-data`; params?: Router.UnknownInputParams; } | { pathname: `/report-source`; params?: Router.UnknownInputParams; } | { pathname: `/thank-you`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/department/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/department/groundwater`; params?: Router.UnknownInputParams; } | { pathname: `/department/history`; params?: Router.UnknownInputParams; } | { pathname: `/department/login`; params?: Router.UnknownInputParams; } | { pathname: `/department/signup`; params?: Router.UnknownInputParams; } | { pathname: `/department/springs`; params?: Router.UnknownInputParams; } | { pathname: `/department/streamshed`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/no-location`; params?: Router.UnknownOutputParams; } | { pathname: `/offline-data`; params?: Router.UnknownOutputParams; } | { pathname: `/report-source`; params?: Router.UnknownOutputParams; } | { pathname: `/thank-you`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/department/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/department/groundwater`; params?: Router.UnknownOutputParams; } | { pathname: `/department/history`; params?: Router.UnknownOutputParams; } | { pathname: `/department/login`; params?: Router.UnknownOutputParams; } | { pathname: `/department/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/department/springs`; params?: Router.UnknownOutputParams; } | { pathname: `/department/streamshed`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/no-location${`?${string}` | `#${string}` | ''}` | `/offline-data${`?${string}` | `#${string}` | ''}` | `/report-source${`?${string}` | `#${string}` | ''}` | `/thank-you${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/department/dashboard${`?${string}` | `#${string}` | ''}` | `/department/groundwater${`?${string}` | `#${string}` | ''}` | `/department/history${`?${string}` | `#${string}` | ''}` | `/department/login${`?${string}` | `#${string}` | ''}` | `/department/signup${`?${string}` | `#${string}` | ''}` | `/department/springs${`?${string}` | `#${string}` | ''}` | `/department/streamshed${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/no-location`; params?: Router.UnknownInputParams; } | { pathname: `/offline-data`; params?: Router.UnknownInputParams; } | { pathname: `/report-source`; params?: Router.UnknownInputParams; } | { pathname: `/thank-you`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/department/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/department/groundwater`; params?: Router.UnknownInputParams; } | { pathname: `/department/history`; params?: Router.UnknownInputParams; } | { pathname: `/department/login`; params?: Router.UnknownInputParams; } | { pathname: `/department/signup`; params?: Router.UnknownInputParams; } | { pathname: `/department/springs`; params?: Router.UnknownInputParams; } | { pathname: `/department/streamshed`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
